-- Swing2Go: tabeller. Priser lagras i öre (heltal).

create type grade as enum ('A', 'B', 'C');
create type order_status as enum ('ny', 'packas', 'skickad', 'levererad', 'avbruten');
create type user_role as enum ('kund', 'admin');

create table brands (
  id uuid primary key default gen_random_uuid(),
  name text not null unique
);

create table products (
  id uuid primary key default gen_random_uuid(),
  brand_id uuid not null references brands(id),
  model text not null,
  slug text not null unique,
  description text not null default '',
  grade grade not null,
  active boolean not null default true,
  is_demo boolean not null default false,
  created_at timestamptz not null default now()
);

create table product_variants (
  id uuid primary key default gen_random_uuid(),
  product_id uuid not null references products(id) on delete cascade,
  pack_size smallint not null check (pack_size in (6, 12)),
  price_ore integer not null check (price_ore > 0),
  stock integer not null default 0 check (stock >= 0),
  unique (product_id, pack_size)
);

create table product_images (
  id uuid primary key default gen_random_uuid(),
  product_id uuid not null references products(id) on delete cascade,
  storage_path text not null,
  sort_order integer not null default 0
);

create table profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null default '',
  phone text,
  role user_role not null default 'kund',
  created_at timestamptz not null default now()
);

create table addresses (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  street text not null,
  postal_code text not null,
  city text not null,
  is_default boolean not null default false
);

create table orders (
  id uuid primary key default gen_random_uuid(),
  order_number integer generated by default as identity (start with 1001) unique,
  user_id uuid references auth.users(id) on delete set null,
  status order_status not null default 'ny',
  subtotal_ore integer not null,
  shipping_ore integer not null,
  total_ore integer not null,
  customer_name text not null,
  customer_email text not null,
  customer_phone text,
  ship_street text not null,
  ship_postal_code text not null,
  ship_city text not null,
  created_at timestamptz not null default now()
);

create table order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references orders(id) on delete cascade,
  variant_id uuid references product_variants(id) on delete set null,
  -- Kopierat vid köp så att gamla ordrar ser rätt ut även om produkten ändras.
  product_name text not null,
  grade grade not null,
  pack_size smallint not null,
  quantity integer not null check (quantity > 0),
  unit_price_ore integer not null
);

create index on products (active);
create index on product_variants (product_id);
create index on orders (user_id, created_at desc);
create index on order_items (order_id);

-- Skapa profil automatiskt när någon registrerar sig.
create function handle_new_user() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  insert into profiles (id, full_name)
  values (new.id, coalesce(new.raw_user_meta_data->>'full_name', ''));
  return new;
end $$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function handle_new_user();
